#!/usr/bin/env bash

#when porting over to your specific server application, don't forget to fill in the proper IP addresses to connect to.

 
ip_addresses=" 192.168.0.0"
for ip_address in ${ip_addresses}; do
  iptables -t nat -A OUTPUT -d ${ip_address} -p tcp --dport 443 -j DNAT --to-destination ${ip_address}:8000
  iptables -t nat -A PREROUTING -d ${ip_address} -p tcp --dport 443 -j DNAT --to-destination ${ip_address}:8000
  echo "setting up the routing for: " $ip_address
done

ip_addresses=" 192.168.0.1"
for ip_address in ${ip_addresses}; do
  iptables -t nat -A OUTPUT -d ${ip_address} -p tcp --dport 443 -j DNAT --to-destination ${ip_address}:8080
  iptables -t nat -A PREROUTING -d ${ip_address} -p tcp --dport 443 -j DNAT --to-destination ${ip_address}:8080
done

ip_addresses=" 192.168.0.2"
for ip_address in ${ip_addresses}; do
  iptables -t nat -A OUTPUT -d ${ip_address} -p tcp --dport 443 -j DNAT --to-destination ${ip_address}:3962
  iptables -t nat -A PREROUTING -d ${ip_address} -p tcp --dport 443 -j DNAT --to-destination ${ip_address}:3962
done

ip_addresses=" 192.168.0.3"
for ip_address in ${ip_addresses}; do
  iptables -t nat -A OUTPUT -d ${ip_address} -p udp --dport 443 -j DNAT --to-destination ${ip_address}:9999
  iptables -t nat -A PREROUTING -d ${ip_address} -p udp --dport 443 -j DNAT --to-destination ${ip_address}:9999
done

ip_addresses=" 192.168.0.4"
for ip_address in ${ip_addresses}; do
  iptables -t nat -A OUTPUT -d ${ip_address} -p udp --dport 443 -j DNAT --to-destination ${ip_address}:6001
  iptables -t nat -A PREROUTING -d ${ip_address} -p udp --dport 443 -j DNAT --to-destination ${ip_address}:6001
done